# Generated by Django 5.0.6 on 2026-04-16 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('icon', models.CharField(default='fa-solid fa-star', max_length=100, verbose_name='Иконка (Font Awesome класс)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки с формы обратной связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вопрос (FAQ)',
                'verbose_name_plural': 'FAQ — Часто задаваемые вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL-slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (₽)')),
                ('duration_minutes', models.PositiveIntegerField(default=150, help_text='Примерная длительность процедуры', verbose_name='Длительность (мин.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('icon', models.CharField(default='fa-solid fa-eye', help_text='Например: fa-solid fa-eye, fa-solid fa-feather', max_length=100, verbose_name='Иконка (Font Awesome класс)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(default='Мастер Анна', max_length=100, verbose_name='Имя мастера')),
                ('hero_title', models.CharField(default='Подчеркни свою красоту', max_length=200, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.CharField(default='Наращивание ресниц и ламинирование бровей — с заботой о каждой детали', max_length=300, verbose_name='Подзаголовок Hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Картинка Hero')),
                ('hero_video_url', models.URLField(blank=True, help_text='Опционально: ссылка на видео для Hero-блока', verbose_name='Ссылка на видео (YouTube/MP4)')),
                ('phone', models.CharField(default='+7 (999) 000-00-00', max_length=30, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Телефон')),
                ('whatsapp', models.CharField(default='79990000000', help_text='Только цифры, без +, пробелов и скобок. Например: 79990000000', max_length=30, verbose_name='WhatsApp (номер без +)')),
                ('instagram', models.CharField(blank=True, default='beauty_master', max_length=100, verbose_name='Instagram (логин без @)')),
                ('address', models.CharField(default='г. Москва, ул. Пример, д. 1', max_length=300, verbose_name='Адрес')),
                ('email', models.EmailField(default='master@example.com', max_length=254, verbose_name='Email для уведомлений')),
                ('work_hours', models.CharField(default='Пн–Вс: 09:00–21:00', max_length=100, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('date', 'time'), name='unique_active_booking_slot'),
        ),
    ]
