# Generated by Django 5.0.6 on 2026-04-21 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1920×1080 и больше', null=True, upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Картинка Hero'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Необязательно. Отображается над описанием.', max_length=150, verbose_name='Название работы')),
                ('description', models.CharField(blank=True, help_text='Необязательно. Показывается в lightbox.', max_length=300, verbose_name='Короткое описание')),
                ('image', models.ImageField(help_text='JPG, PNG, WEBP (до 5 МБ).', upload_to='portfolio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='main.service', verbose_name='Связанная услуга')),
            ],
            options={
                'verbose_name': 'Работа (портфолио)',
                'verbose_name_plural': 'Портфолио — работы мастера',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
