# Generated by Django 5.2 on 2026-04-23 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_service_image_alter_sitesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_video_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Загрузите MP4/WebM файл. Если загружен файл — он приоритетнее ссылки.', null=True, upload_to='hero/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Видео-файл Hero'),
        ),
    ]
