# Generated by Django 5.2 on 2026-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sitesettings_hero_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='SEO заголовок'),
        ),
    ]
